Create LSP_P-MAT.yml
kockatykalendar/data pull request #198
Opened 2022-07-28 17:54 UTC by Mati48

2022-07-29 09:26 UTC, krtko1 requested changes
ak toto je akcia pre vedúcich, takže keď tak zmeniť ročníky ale tiež neviem či to tu úplne chce byť

2022-07-29 09:44 UTC, Mati48 commented
> ak toto je akcia pre vedúcich, takže keď tak zmeniť ročníky ale tiež neviem či to tu úplne chce byť

Prišlo mi to zvláštne no v ideálnych termínoch to bolo zaznačené, že to ma´me dať na stránku a že účastničia základoškoláci...

2022-07-29 09:47 UTC, Mati48 commented
Napíšem Paľovi.

2022-07-29 10:07 UTC, Mati48 commented
> Napíšem Paľovi.

Paľo potvrdil, že to chce byť pre sš a vš a že si to tak prosia na stránku.

2022-07-29 10:09 UTC, Mati48 commented
> ak toto je akcia pre vedúcich, takže keď tak zmeniť ročníky ale tiež neviem či to tu úplne chce byť

Jop, hmm ale asi nevieme povedať ss1 až nekonečno...

2022-07-29 10:11 UTC, krtko1 commented
> > ak toto je akcia pre vedúcich, takže keď tak zmeniť ročníky ale tiež neviem či to tu úplne chce byť
> 
> Jop, hmm ale asi nevieme povedať ss1 až nekonečno...

vieme treba dať max: null

2022-08-24 22:42 UTC, krtko1 approved these changes

2022-08-24 22:42 UTC, merged