Change contestants schema
kockatykalendar/data pull request #29
Opened 2020-12-30 10:45 UTC by ano95

Odteraz je min aj max povinný, avšak pre open súťaže môžu byť `null`.

Closes #26.

Pls review @Zajozor a @krtko1 by mohol skontrolovať akcie, ktoré som zmenil. Pomenil som to síce podľa aktuálnej implementácie, ktorú používa frontend, ale z toho vyplýva, že napr. `advent` je len pre `ss1`?

2020-12-30 11:09 UTC, krtko1 requested changes

2020-12-30 11:09 UTC, krtko1 commented on data/2020_21/04_december/advent.yml
> +  max: ss1
podľa mňa skôr `null`, možno aj min by mohlo byť `null` ale keďže to má "stredoškolskú" úroveň, tak tam môžme nechať asi aj `ss1`

2020-12-30 12:17 UTC, krtko1 approved these changes

2021-01-01 14:16 UTC, Zajozor approved these changes
Zmena schemy je fajn.

mergni si najprv to CI, nech to rovno skontroluje :D

jednym okom som popozeral a myslim ze si upravil vsetko co treba, spravne. (=nezabudol si na nejaky event/neni tam nejaka blbost)

2021-01-01 16:11 UTC, ano95 commented
Tak, ja som si ten check zbehol u seba, že :slightly_smiling_face:

2021-01-01 16:16 UTC, merged