Update 2_sezam.yml
kockatykalendar/data pull request #6
Opened 2020-10-30 16:00 UTC by Zajozor

2020-10-31 01:13 UTC, krtko1 approved these changes

2020-11-01 18:12 UTC, ano95 requested changes
stále má ta akcia 10 mesiacov, je to správne? :smile:

2020-11-01 20:18 UTC, Zajozor commented
lol

2020-11-02 10:14 UTC, ano95 approved these changes

2020-11-16 10:50 UTC, merged