2021-tmf: add event
kockatykalendar/data pull request #71
Opened 2021-04-01 14:03 UTC by krtko1

2021-04-01 14:41 UTC, ano95 requested changes
Vieme niekde rozpísať, čo znamená TMF?

2021-04-01 18:47 UTC, krtko1 commented
môžme ale MO, FO, a pod nerozpisujeme. A toto je súťaž z identickej kategórie. Teda možno to chceme adresovať nejak viac globálne.

2021-04-12 15:39 UTC, ano95 approved these changes

2021-04-12 15:39 UTC, ano95 commented
Nie, že by to už bolo aktuálne, ale pre kompletnosť kalendára :sweat_smile:

2021-04-12 15:39 UTC, merged