Import 2020 21
kockatykalendar/data pull request #9
Opened 2020-11-07 08:38 UTC by Zajozor

By @ano95 and @miskadlugosova

2020-11-07 16:00 UTC, krtko1 commented
dúfam, že sa na mňa nehneváte ale prišlo mi rozumnejšie rovno commitnúť tie zmeny

2020-11-07 16:19 UTC, Zajozor commented
@krtko1 diky!

@miskadlugosova mozes si inac pozriet co po tebe bolo upravene, aby si nabuduce vedela :)

2020-11-07 20:21 UTC, ano95 commented
@krtko1 čo si zas chytal schému? :D

2020-11-07 22:45 UTC, Zajozor commented
Tiez by som vynechal tu upravu ze organizers su z enumu ako sme sa uz raz bavili. Ale skoro si to tam prepasoval :D

2020-11-09 15:28 UTC, krtko1 commented
dokelu to som zabudol vrátiť nazad (to som iba kontroloval, či sme konzistentný a teda budú fungovať ikonku)

2020-11-09 15:29 UTC, krtko1 commented
ale ten type bolo treba upraviť keďže to  testovanie piatakov naozaj na nič nesedí

2020-11-09 20:34 UTC, ano95 requested changes
tak @krtko1, rollbackni tých orgov a môžeme mergnúť

2020-11-11 20:17 UTC, ano95 approved these changes

2020-11-12 07:39 UTC, merged